//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Pothosware.SoapySDR {


/// <summary>The RF direction to use for a given function.</summary>
public enum Direction {
  /// <summary>Transmit</summary>
  Tx = 0,
  /// <summary>Receive</summary>
  Rx = 1
}

}
