//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Pothosware.SoapySDR {


/// <summary>Error codes returned from streaming functions.</summary>
public enum ErrorCode {
  /// <summary>No error.</summary>
  None = 0,
  /// <summary>Returned when read has a timeout.</summary>
  Timeout = -1,
  /// <summary>Returned for non-specific stream errors.</summary>
  StreamError = -2,
  /// <summary>Returned when read has data corruption. For example, the driver saw a malformed packet.</summary>
  Corruption = -3,
  /// <summary>Returned when read has an overflow condition. For example, and internal buffer has filled.</summary>
  Overflow = -4,
  /// <summary>Returned when a requested operation or flag setting is not supported by the underlying implementation.</summary>
  NotSupported = -5,
  /// <summary>Returned when a the device encountered a stream time which was expired (late) or too early to process.</summary>
  TimeError = -6,
  /// <summary>Returned when write caused an underflow condition. For example, a continuous stream was interrupted.</summary>
  Underflow = -7
}

}
